import { app } from 'electron'
import { existsSync } from 'node:fs'
import { join } from 'node:path'

/**
 * Where the application icon lives, in development and after packaging.
 *
 * Backstage has no packager yet — `electron-vite` builds the three bundles and
 * stops — so this resolves against both layouts rather than assuming one. When
 * a packager is added, `build/` goes in `extraResources` and the packaged
 * branch below already points at it; nothing here has to change.
 *
 * The assets themselves are generated by `npm run icons` from a single 16x16
 * master. See scripts/make-icons.mjs.
 */

/**
 * The right file for this platform.
 *
 *   Windows  .ico, which carries every size in one file and is what the
 *            taskbar, the title bar and Explorer all read
 *   Linux    .png, which is what `BrowserWindow` accepts there
 *   macOS    neither. The window icon is ignored entirely — the Dock and the
 *            Finder read the icon out of the .app bundle, which is the
 *            packager's job — so this returns null rather than pretending.
 */
function iconFile(): string | null {
  if (process.platform === 'darwin') return null
  return process.platform === 'win32' ? 'icon.ico' : 'icon.png'
}

/**
 * The absolute path, or null if the asset has not been generated.
 *
 * Null rather than a guessed path: `BrowserWindow` given a path that does not
 * exist silently falls back to the default Electron icon, which is exactly the
 * failure this module is here to prevent and is invisible in a screenshot. The
 * caller logs it instead, so a missing `npm run icons` is a line in the console
 * rather than a mystery.
 */
export function appIconPath(): string | null {
  const file = iconFile()
  if (!file) return null

  const candidates = app.isPackaged
    ? [
        join(process.resourcesPath, 'build', file),
        join(process.resourcesPath, file)
      ]
    : // The main bundle runs from out/main, so the repository root is two up.
      [join(__dirname, '..', '..', 'build', file)]

  return candidates.find((path) => existsSync(path)) ?? null
}

/**
 * Give the application its identity, before any window exists.
 *
 * `setAppUserModelId` is the Windows-specific half and is easy to skip. Without
 * it, Windows groups the window under whatever it infers from the executable —
 * in development, "Electron" — so the taskbar shows the Electron logo and the
 * icon set on the window has no effect on the grouped button. Setting it makes
 * the taskbar entry Backstage's own, and it is also what notifications are
 * attributed to.
 */
export function applyAppIdentity(): void {
  app.setName('Backstage')

  if (process.platform === 'win32') {
    app.setAppUserModelId('com.backstage.app')
  }

  if (!appIconPath() && process.platform !== 'darwin') {
    console.warn(
      '[icon] build/icon.* is missing, so the default Electron icon will be ' +
        'used. Run `npm run icons` to generate it.'
    )
  }
}
