import { defineCast } from '../../characters/defineCast'
import type { CharacterDef } from '../../characters/character.types'

/**
 * A lab crew. Same agents, in coats and respirator straps.
 *
 * Six of the eight used to share `hairStyle: 'short'` under identical lab
 * coats, which is as close to eight copies of one sprite as this codebase ever
 * came. The coats stay — they are the world — so the separation has to come
 * from heads: one bald, one goateed, one topknot, one afro, and no two faces
 * built the same way.
 */
export const labCharacters: CharacterDef[] = defineCast([
  {
    id: 'walter',
    agentId: 'agent-1',
    name: 'Walter',
    role: 'Lead Chemist',
    homeDesk: 0,
    // Bald and bearded, with glasses: the only skull in the room, and the
    // strongest silhouette in any of the six worlds.
    skin: '#EFC49F',
    hair: '#7D7A74',
    hairStyle: 'bald',
    outfit: '#D6D8C6',
    shirt: '#FBFBF2',
    accent: '#6E8F4A',
    trousers: '#4A5348',
    shoes: '#1B2019',
    glasses: true,
    build: 'regular',
    posture: 'forward',
    outfitStyle: 'labcoat',
    expression: 'serious',
    faceWidth: 'wide',
    eyeSpacing: 'close',
    browShape: 'heavy',
    noseShape: 'broad',
    jaw: 'square',
    facialHair: 'goatee',
    facialHairColor: '#8A8780'
  },
  {
    id: 'jesse',
    agentId: 'agent-2',
    name: 'Jesse',
    role: 'Lab Technician',
    homeDesk: 1,
    skin: '#EDBE93',
    hair: '#C7A45E',
    hairStyle: 'buzz',
    outfit: '#7BA05B',
    shirt: '#EFEEE0',
    trousers: '#3E4A3C',
    shoes: '#1B2019',
    smirk: true,
    build: 'slim',
    posture: 'slouched',
    outfitStyle: 'hoodie',
    accessory: 'headphones',
    accessoryColor: '#FFC94F',
    faceWidth: 'narrow',
    eyeSpacing: 'wide',
    browShape: 'arched',
    noseShape: 'small',
    jaw: 'narrow',
    facialHair: 'stubble'
  },
  {
    id: 'gus',
    agentId: 'agent-3',
    name: 'Gus',
    role: 'Operations',
    homeDesk: 2,
    // The most controlled face in the building: narrow, level, unreadable.
    skin: '#B8865C',
    hair: '#221A14',
    hairStyle: 'short',
    outfit: '#3B4A44',
    shirt: '#E4E6DA',
    accent: '#6E8F4A',
    trousers: '#2F3A35',
    shoes: '#1B2019',
    glasses: true,
    build: 'slim',
    posture: 'rigid',
    outfitStyle: 'suit',
    expression: 'calm',
    faceWidth: 'narrow',
    eyeSpacing: 'regular',
    browShape: 'flat',
    noseShape: 'straight',
    jaw: 'narrow'
  },
  {
    id: 'saul',
    agentId: 'agent-4',
    name: 'Saul',
    role: 'Negotiator',
    homeDesk: 0,
    // A comb-over that fools nobody, and the only suit on the floor.
    skin: '#F0C6A0',
    hair: '#6A4E30',
    hairStyle: 'slick',
    outfit: '#9A8248',
    shirt: '#FBFBF2',
    accent: '#A8623A',
    trousers: '#5E5233',
    shoes: '#1B2019',
    smirk: true,
    build: 'regular',
    posture: 'relaxed',
    outfitStyle: 'suit',
    accessory: 'briefcase',
    accessoryColor: '#8A6236',
    faceWidth: 'wide',
    eyeSpacing: 'wide',
    browShape: 'arched',
    noseShape: 'broad',
    jaw: 'soft'
  },

  /* Extra hands on the bench, brought in as the workload grows. */
  {
    id: 'mike',
    agentId: 'agent-5',
    name: 'Mike',
    role: 'Security',
    homeDesk: 1,
    skin: '#EFC49F',
    hair: '#9A9A94',
    hairStyle: 'buzz',
    outfit: '#4A4A48',
    shirt: '#E4E6DA',
    trousers: '#3A3A38',
    build: 'broad',
    posture: 'rigid',
    outfitStyle: 'coat',
    accessory: 'earpiece',
    accessoryColor: '#FFC94F',
    expression: 'tired',
    faceWidth: 'wide',
    eyeSpacing: 'close',
    browShape: 'heavy',
    noseShape: 'broad',
    jaw: 'square'
  },
  {
    id: 'skyler',
    agentId: 'agent-6',
    name: 'Skyler',
    role: 'Bookkeeping',
    homeDesk: 2,
    skin: '#F6D2AE',
    hair: '#D7B96A',
    hairStyle: 'waves',
    outfit: '#5A7A9A',
    shirt: '#FBFBF2',
    trousers: '#3E5266',
    build: 'slim',
    posture: 'upright',
    outfitStyle: 'blazer',
    accessory: 'tablet',
    accessoryColor: '#FFC94F',
    expression: 'skeptical',
    faceWidth: 'narrow',
    eyeSpacing: 'regular',
    browShape: 'angled',
    noseShape: 'small',
    jaw: 'narrow'
  },
  {
    id: 'hank',
    agentId: 'agent-7',
    name: 'Hank',
    role: 'Compliance',
    homeDesk: 0,
    skin: '#EDBE93',
    hair: '#7A6A54',
    hairStyle: 'short',
    outfit: '#7A6A4A',
    shirt: '#EFEEE0',
    trousers: '#4A4234',
    build: 'broad',
    posture: 'slouched',
    outfitStyle: 'shirt',
    accessory: 'badge',
    expression: 'friendly',
    faceWidth: 'wide',
    eyeSpacing: 'regular',
    browShape: 'flat',
    noseShape: 'broad',
    jaw: 'square',
    facialHair: 'moustache',
    facialHairColor: '#8A7A62'
  },
  {
    id: 'todd',
    agentId: 'agent-8',
    name: 'Todd',
    role: 'Assistant',
    homeDesk: 1,
    skin: '#F0C6A0',
    hair: '#8A6A3A',
    hairStyle: 'parted',
    outfit: '#9AA08A',
    shirt: '#FBFBF2',
    trousers: '#4A5248',
    build: 'slim',
    posture: 'upright',
    outfitStyle: 'labcoat',
    accessory: 'pen',
    accessoryColor: '#FFC94F',
    expression: 'friendly',
    faceWidth: 'narrow',
    eyeSpacing: 'close',
    browShape: 'arched',
    noseShape: 'small',
    jaw: 'soft'
  }
])
