import { defineCast } from '../../characters/defineCast'
import type { CharacterDef } from '../../characters/character.types'

/**
 * A paper-company branch. Same agents, different job titles.
 *
 * Written through `defineCast` rather than by hand, so the shading is derived
 * and every face is stated in a few lines. The test is the same one every cast
 * is held to: tellable apart as black silhouettes, and tellable apart again
 * from the neck up.
 */
export const officeCharacters: CharacterDef[] = defineCast([
  {
    id: 'michael',
    agentId: 'agent-1',
    name: 'Michael',
    role: 'Regional Manager',
    homeDesk: 0,
    // Soft everything: round jaw, wide eyes, arched brows. The most eager
    // face in the building, which is the joke.
    skin: '#F0C6A0',
    hair: '#33251C',
    hairStyle: 'parted',
    outfit: '#3C4657',
    shirt: '#FFFFFF',
    accent: '#8C3F3F',
    trousers: '#2E3542',
    shoes: '#20242B',
    build: 'regular',
    posture: 'upright',
    outfitStyle: 'suit',
    expression: 'friendly',
    faceWidth: 'wide',
    eyeSpacing: 'wide',
    browShape: 'arched',
    noseShape: 'small',
    jaw: 'soft'
  },
  {
    id: 'dwight',
    agentId: 'agent-2',
    name: 'Dwight',
    role: 'Sales Lead',
    homeDesk: 1,
    // Glasses, a hard side parting and a heavy brow: rigid from every angle.
    skin: '#EFC49F',
    hair: '#8A6A3A',
    hairStyle: 'parted',
    outfit: '#6E7043',
    shirt: '#EDE6CE',
    accent: '#7A5A2E',
    trousers: '#4A4B2C',
    shoes: '#20242B',
    glasses: true,
    build: 'regular',
    posture: 'rigid',
    outfitStyle: 'suit',
    accessory: 'badge',
    expression: 'serious',
    faceWidth: 'narrow',
    eyeSpacing: 'close',
    browShape: 'heavy',
    noseShape: 'straight',
    jaw: 'square'
  },
  {
    id: 'pam',
    agentId: 'agent-3',
    name: 'Pam',
    role: 'Coordinator',
    homeDesk: 2,
    // Long hair and the narrowest face in the branch; a quiet, level brow.
    skin: '#F3CBA4',
    hair: '#8A6134',
    hairStyle: 'waves',
    outfit: '#7F8F9E',
    shirt: '#FFFFFF',
    trousers: '#41505C',
    shoes: '#20242B',
    build: 'slim',
    posture: 'upright',
    outfitStyle: 'cardigan',
    accessory: 'notebook',
    accessoryColor: '#FFC94F',
    expression: 'calm',
    faceWidth: 'narrow',
    eyeSpacing: 'regular',
    browShape: 'flat',
    noseShape: 'small',
    jaw: 'narrow'
  },
  {
    id: 'jim',
    agentId: 'agent-4',
    name: 'Jim',
    role: 'Analyst',
    homeDesk: 0,
    // Swept hair, close-set eyes, one raised brow: mid-glance at the camera.
    skin: '#EDBE93',
    hair: '#4A3524',
    hairStyle: 'swept',
    outfit: '#4E5A6B',
    shirt: '#DDE6EE',
    accent: '#5C6B8A',
    trousers: '#39424F',
    shoes: '#20242B',
    build: 'slim',
    posture: 'relaxed',
    outfitStyle: 'suit',
    smirk: true,
    faceWidth: 'narrow',
    eyeSpacing: 'close',
    browShape: 'angled',
    noseShape: 'straight',
    jaw: 'narrow'
  },

  /* The rest of the branch, brought in as the workload grows. */
  {
    id: 'stanley',
    agentId: 'agent-5',
    name: 'Stanley',
    role: 'Sales',
    homeDesk: 1,
    skin: '#7A5236',
    hair: '#2A2320',
    hairStyle: 'buzz',
    outfit: '#4A4A55',
    shirt: '#E4E8EE',
    accent: '#7A3A3A',
    trousers: '#3A3A44',
    glasses: true,
    build: 'broad',
    posture: 'slouched',
    outfitStyle: 'shirt',
    expression: 'tired',
    faceWidth: 'wide',
    eyeSpacing: 'regular',
    browShape: 'heavy',
    noseShape: 'broad',
    jaw: 'square',
    facialHair: 'moustache',
    facialHairColor: '#4A4038'
  },
  {
    id: 'kevin',
    agentId: 'agent-6',
    name: 'Kevin',
    role: 'Accounting',
    homeDesk: 2,
    skin: '#EFC49F',
    hair: '#4A3524',
    hairStyle: 'short',
    outfit: '#6A7A5A',
    shirt: '#F2F2F0',
    trousers: '#4A5240',
    build: 'broad',
    posture: 'slouched',
    outfitStyle: 'shirt',
    accessory: 'mug',
    accessoryColor: '#E8E4DA',
    expression: 'calm',
    faceWidth: 'wide',
    eyeSpacing: 'close',
    browShape: 'flat',
    noseShape: 'broad',
    jaw: 'soft',
    facialHair: 'stubble'
  },
  {
    id: 'angela',
    agentId: 'agent-7',
    name: 'Angela',
    role: 'Accounting Lead',
    homeDesk: 0,
    skin: '#F3CBA4',
    hair: '#C7A45E',
    hairStyle: 'bun',
    outfit: '#5A7A6A',
    shirt: '#FFFFFF',
    trousers: '#3E5248',
    build: 'slim',
    posture: 'rigid',
    outfitStyle: 'cardigan',
    expression: 'skeptical',
    faceWidth: 'narrow',
    eyeSpacing: 'close',
    browShape: 'angled',
    noseShape: 'small',
    jaw: 'narrow'
  },
  {
    id: 'oscar',
    agentId: 'agent-8',
    name: 'Oscar',
    role: 'Analyst',
    homeDesk: 1,
    skin: '#C08A5A',
    hair: '#241A16',
    hairStyle: 'slick',
    outfit: '#3E4A5E',
    shirt: '#E8EDF3',
    accent: '#5C6B8A',
    trousers: '#333E4E',
    glasses: true,
    build: 'regular',
    posture: 'upright',
    outfitStyle: 'suit',
    expression: 'focused',
    faceWidth: 'regular',
    eyeSpacing: 'regular',
    browShape: 'flat',
    noseShape: 'straight',
    jaw: 'square'
  }
])
